### ISSUE TITLE
Error installing MutScape

### ISSUE THREAD

**Issue by lordaaa999** [anitalu724/MutScape#1]
Hi,
Thank you for developing this useful tool.
I encountered an error when I tried to install MutScape using quick installation.
The error message is as follows:

===============
Install PyVCF...
 
Collecting PyVCF
  Using cached PyVCF-0.6.8.tar.gz (34 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/lordaaa/miniconda3/envs/MutScape/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yhsoj5_v/pyvcf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yhsoj5_v/pyvcf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g_fi1ew8
         cwd: /tmp/pip-install-yhsoj5_v/pyvcf/
    Complete output (1 lines):
    error in PyVCF setup command: use_2to3 is invalid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
==================

The environment I use is a clean, newly created Google Cloud VM, and the OS is Ubuntu 18.04.6 LTS.
Any suggestions?

Thank you,
Yi-Chen

**Comment by anitalu724** [comment]
@lordaaa999  Did you try install PyVCF using anaconda?
[PyVCF anaconda website](https://anaconda.org/conda-forge/pyvcf)

**Comment by lordaaa999** [comment]
@anitalu724 I did not try install PyVCF using anaconda. However, I used my local workstation (Ubuntu 16.04 LTS) to install MutScape instead, and it worked well now.  Thank you for your suggestion.
