### ISSUE TITLE
Killed in the step of Start VCF combination

### ISSUE THREAD

**Issue by bio-rain** [anitalu724/MutScape#2]
Hi, I use mutect2 to make vcf file, and put it into MutScape, then I get the error message as the title says.
the step of  "Start VCF combination", "Reading TSV file" and "Formalizing VCF files" are passed, and Killed in the step of Start VCF combination (only print Killed), so I do not know what happen.
Thanks for your answer.

**Comment by anitalu724** [comment]
Can you give me a screenshot of part of your mutect2 vcf file so that I can have a more precise judgment? Thanks a lot~

**Comment by anitalu724** [comment]
> Hi, I use mutect2 to make vcf file, and put it into MutScape, then I get the error message as the title says. the step of "Start VCF combination", "Reading TSV file" and "Formalizing VCF files" are passed, and Killed in the step of Start VCF combination (only print Killed), so I do not know what happen. Thanks for your answer.

Can you give me a screenshot of part of your mutect2 vcf file so that I can have a more precise judgment? Thanks a lot~
